appname/posts/models.py
from appname import db
from datetime import datetime

# models here
class Post(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    title = db.Column(db.String(100), nullable = False, unique=True)
    content = db.Column(db.Text, nullable = False)
    date_create = db.Column(db.DateTime, nullable = False, default = datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable = False)

    def __repr__(self):
        return f"Post('{self.title}', '{self.date_create}')"

appname/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import Length, DataRequired, ValidationError
from appname.posts.models import Post


class PostForm(FlaskForm):
    title = StringField("Title", validators=[Length(min = 2, max = 100), DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired(), Length(min = 2)])
    submit = SubmitField("Post")

    def validate_title(self, title):
        post = Post.query.filter_by(title= title.data).first()
        if post:
            raise ValidationError("this title is already taken you can search with this name to get it (:")

class PostEditForm(FlaskForm):
    title = StringField("Title", validators=[Length(min = 2, max = 100)])
    content = TextAreaField("Content", validators=[Length(min = 2)])
    submit = SubmitField("Save")
    def validate_title(self, title):
        post = Post.query.filter_by(title= title.data).first()
        if post and post.content == self.content:
            raise ValidationError("this title is already taken you can search with this name to get it (:")

appname/main/routes.py
from appname.posts.models import Post
from flask import render_template, request
from flask import Blueprint

main = Blueprint("main", __name__)


@main.route('/')
@main.route('/home', methods = ["POST", "GET"])
def homepage():
    page = request.args.get("page", 1, type= int)
    posts = Post.query\
        .order_by(Post.date_create.desc())\
        .paginate(page = page, per_page = 5)
    return render_template("homepage.html", title = "Home", posts = posts)


@main.route("/about")
def about():
    return render_template("about.html")

appname/posts/routes.py
from flask import render_template, redirect, url_for, flash, request, Blueprint
from appname import db
from appname.posts.forms import PostForm, PostEditForm
from appname.posts.models import Post
from flask_login import current_user, login_required

# your routes here

posts = Blueprint("posts", __name__)

@posts.route("/post", methods = ["POST", "GET"])
@login_required
def Post_page():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title = form.title.data, content = form.content.data, user_id = current_user.id)
        db.session.add(post)
        db.session.commit()
        flash("your post added successfully", "success")
        return redirect(url_for("main.homepage"))
    else:
        return render_template("post.html", title = "Create Post", form = form)


# to check that user change any of his information or not
def validate_post_edit(title, content):
    post = Post.query.filter_by(title = title.data, content = content.data).first()
    if post:
        return True

@posts.route("/post/<int:post_id>/update", methods = ["POST", "GET"])
@login_required
def post_edit(post_id):
    form = PostEditForm()
    post = Post.query.get_or_404(post_id)
    if post.author == current_user:
        if form.validate_on_submit():
            if validate_post_edit(form.title, form.content):
                flash("you don't make any changes to save it", "warning")
                return redirect(url_for("posts.post_edit", post_id=post_id))
            else:
                post.title = form.title.data
                post.content = form.content.data
                db.session.commit()
                flash("Post Edit Successfully", "success")
                return redirect(url_for("posts.post_edit",post_id = post_id))
        elif request.method == 'GET':
            form.title.data = post.title
            form.content.data = post.content
        return render_template("post_edit.html", post= post, form = form)
    else:
        return render_template("errors/403.html")



@posts.route("/post_view/<int:post_id>")
@login_required
def post_full(post_id):
    post = Post.query.filter_by(id = post_id).first()
    return render_template("post_full_view.html", post = post)

# to delete post
def delete(post):
    db.session.delete(post)
    db.session.commit()
    flash("your post has been deleted", "success")

@posts.route("/deletePost/<int:post_id>/<string:place>", methods = ["POST", "GET"])
def delete_post(post_id,place: str):
    post = Post.query.get_or_404(int(post_id))
    if place == "account_page":
        delete(post)
        return redirect(url_for("users.account", user_id= current_user.id))
    else:
        delete(post)
        return redirect(url_for("main.homepage"))

appname/users/routes.py
from flask import render_template, redirect, url_for, flash, request, Blueprint
from appname import app, db, by
from appname.users.forms import LoginForm, RegistrationFrom, ChangeInformationForm, ForgetPasswordForm, ResetPasswordForm, ChangePasswordForm
from appname.users.models import User
from flask_login import login_user, current_user, logout_user, login_required
from .utils import send_reset_email, save_image
import os
from appname.posts.models import Post


users = Blueprint("users", __name__)

@users.route("/login", methods = ["post", "get"])
def login():
    loginform = LoginForm()
    if loginform.validate_on_submit():
        user = User.query.filter_by(email = loginform.email.data).first()
        if user and by.check_password_hash(user.password, loginform.password.data):
            login_user(user, remember= loginform.remember_me.data)
            next_page = request.args.get('next')
            flash(f"login done successful {current_user.username}", "info")
            if next_page:
                return redirect(next_page)
            else:
                return redirect(url_for("main.homepage"))
        else:
            flash("your data is not valid", "danger")
    return render_template("login_page.html", form_login= loginform, title="Login")

@users.route("/signup", methods = ["post", "get"])
def signup():
    register_form = RegistrationFrom()
    if register_form.validate_on_submit():
        global user_registration
        hashed_password = by.generate_password_hash(register_form.password.data).decode('utf-8')
        user_registration = User(username= register_form.username.data, password= hashed_password, email= register_form.email.data)
        send_reset_email(user_registration, register_form,"registration")
        flash("check your email to confirm it, you can found it in spam field", "success")
        return redirect(url_for("users.login"))
    else:
        return render_template("register.html", form = register_form, title = "Registration")

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("users.login"))


@users.route("/account/<int:user_id>", methods = ['post', 'get'])
@login_required
def account(user_id):
    global form_Change
    form_Change = ChangeInformationForm()
    image = url_for('static', filename= 'imgs/profile_images/' + current_user.image_file)
    user = User.query.filter_by(id = user_id).first()
    if user:
        if user != current_user:
            return redirect(url_for("users.account_view", user_id = user.id))
    else:
        return render_template("errors/404.html")
    page = request.args.get("page", 1, type= int)
    posts = Post.query.\
        order_by(Post.date_create.desc())\
        .filter_by(author = user).\
        paginate(page= page, per_page= 5)
    if request.method == "POST":
        if request.form.get('action1') == "remove image":
            if user.image_file == "default.jpg":
                flash("you don't put any new photos to remove", "warning")
                return redirect(url_for("users.account", user_id = user.id))
            else:
                old_pic_path = os.path.join(app.root_path, 'static/imgs/profile_images', user.image_file)
                os.remove(old_pic_path)
                user.image_file = "default.jpg"
                db.session.commit()
                flash("photo removed", "success")
                return redirect(url_for("users.account", user_id = user.id))
    if form_Change.validate_on_submit():
        if validate_user_input(form_Change.username, form_Change.email, form_Change.image_name):
            flash("you don't enter new data to change it", "warning")
            return redirect(url_for("users.account", user_id = user.id))
        user.username = form_Change.username.data
        if form_Change.image_name.data:
            image_save = save_image(form_Change.image_name.data)
            user.image_file = image_save
        db.session.commit()
        if validate_email(form_Change, user.id):
            flash("Please Check Your Mail to confirm your Email, If you doesn't found it, check spam", "success")
            return redirect(url_for("main.homepage"))
        flash("Account Information has been changed", "success")
        return redirect(url_for("users.account", user_id = user.id))
    elif request.method == 'GET':
        form_Change.username.data = user.username
        form_Change.email.data = user.email
    return render_template('account.html', title = 'account', img = image, form = form_Change, posts = posts)

@users.route("/account_<int:user_id>")
def account_view(user_id):
    user = User.query.filter_by(id = user_id).first()
    if user:
        if user == current_user:
            return redirect(url_for("users.account", user_id = user_id))
    else:
        return render_template("errors/404.html")
    page = request.args.get("page", 1, type= int)
    posts = Post.query\
        .filter_by(author = user)\
        .order_by(Post.date_create.desc()).\
        paginate(page = page, per_page= 5)
    if user:
        return render_template("account_another.html", user = user, posts = posts)
    else:
        return render_template("errors/404.html")

@users.route("/forget password", methods = ["POST", "GET"])
def forget_password():
    if current_user.is_authenticated:
        return redirect(url_for("main.homepage"))
    form = ForgetPasswordForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email = form.email.data).first()
        send_reset_email(user, form,"resetpassword")
        flash("Check Your Email Inbox To Reset Password", "info")
        return redirect(url_for("users.login"))
    else:
        return render_template("forget_password.html", form = form, title = "Forget Password")

@users.route("/reset password/<token>/<string:action>", methods = ["POST", "GET"])
def reset_token(token, action):
    if action == "forget_password":
        user = User.verify_reset_token(token)
        if user is None:
            flash("that is invalid or expired token", "warning")
            return redirect(url_for("users.forget_password"))
        form = ResetPasswordForm()
        if form.validate_on_submit():
            if by.check_password_hash(user.password, form.password.data):
                flash("you don't change any thing please enter new password", "warning")
                return redirect(url_for("users.reset_token", token=token, _external=True, action= "forget_password"))
            else:
                hashed_password = by.generate_password_hash(form.password.data).decode('utf-8')
                user.password = hashed_password
                db.session.commit()
                flash(f"Your password has been updated!, Now you can Login", "success")
                return redirect(url_for("users.login"))
        return render_template("reset_password.html", form=form, title="Reset Password")
    elif action == "register":
        db.session.add(user_registration)
        db.session.commit()
        flash(f"account created successfully to {user_registration.username}!, Now you can Login", "success")
        return redirect(url_for("users.login"))

    elif action == "email_confirmation":
        current_user.email = form_Change.email.data
        db.session.commit()
        flash(f"account change email successfully", "success")
        return redirect(url_for("users.account", user_id= current_user.id))
    else:
        form = RegistrationFrom()
        return render_template("register.html", form=form, title="Registration")

# to check that user change any of his information or not
def validate_user_input(username, email, image_name):
    user = User.query.filter_by(username = username.data, email = email.data).first()
    if user and image_name.data == None:
        return True

def validate_email(form, user_id):
    user = User.query.filter_by(id = user_id).first()
    if user and user.email != form.email.data:
        send_reset_email(user, form,"email_confirmation")
        return True

@users.route("/change password /<int:user_id>", methods = ["POST", "GET"])
def change_password(user_id):
    form = ChangePasswordForm()
    user = User.query.filter_by(id = user_id).first()
    if form.validate_on_submit():
        if user:
            if by.check_password_hash(user.password,form.old_password.data):
                if by.check_password_hash(user.password,form.new_password.data):
                    flash("your new password is similar to old password, please change it", "warning")
                    return render_template("change_password.html", form = form)
                else:
                    hashed_password = by.generate_password_hash(form.new_password.data).decode('utf-8')
                    user.password = hashed_password
                    db.session.commit()
                    flash("your password is changed", "success")
                return redirect(url_for("users.account", user_id= user_id))
            else:
                flash("Your old Password is not correct please enter it again", "warning")
                return render_template("change_password.html", form= form)
        else:
            return redirect(url_for("errors"))
    else:
        return render_template("change_password.html", form = form)

appname/templates/account.html
{% extends 'base.html' %}
{% block body %}
    <div class="container">
        <div class = "content-section">
        <br>
            <div class = "media">
                <img alt = "account image"  class="rounded-circle account-img" src = "{{ img }}">
                <div class="media-body">
                    <h2 class="account-heading">{{ current_user.username }}</h2>
                    <p class="text-secondary">{{ current_user.email }}</p>
                    <a class="btn btn-outline-info pr-2 pl-2" href="{{ url_for("users.change_password", user_id = current_user.id) }}"> Change Password </a>
                </div>
            </div>
            <!-- form to the current user to edit his account information -->
            <div class="container">
                <form method="post" action="" novalidate enctype="multipart/form-data">
                    {{ form.hidden_tag() }}
                  <div class="form-group">
                    <legend class="border-bottom mb-4">Account Info</legend>
                      {{ form.username.label(class = "exampleInputEmail1") }}
                      {% if form.username.errors %}
                          {{ form.username(class = "form-control is-invalid") }}
                          <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                  <span>{{ error }}</span>
                            {% endfor %}
                          </div>
                      {% else %}
                          {{ form.username(class = "form-control" ) }}
                      {% endif %}

                  </div>
                  <div class="form-group">
                      {{ form.email.label(class = "form-control-label") }}
                      {% if form.email.errors %}
                          {{ form.email(class = "form-control is-invalid" ) }}
                          <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                  <span>{{ error }}</span>
                            {% endfor %}
                          </div>
                      {% else %}
                          {{ form.email(class = "form-control") }}
                      {% endif %}
                  </div>

                    <div class="form-group">
                        {{ form.image_name.label() }}
                        {{ form.image_name(class = "form-control-file") }}
                        {% if form.image_name.errors %}
                            {% for error in form.image_name.errors %}
                                  <small class="text-danger">{{ error }}</small>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        <input type="submit" value="remove image" name ="action1" class="btn btn-secondary">
                    </div>
                    <br>
                    {{ form.submit(class="btn btn-primary") }}
                <br>
                </form>
            </div>
        </div>
    </div>
    {% if posts.items %}
    {% if posts.items[0].author.id == current_user.id %}
        <div class="container">
        <div class = "content-section">
            <h2> Posts </h2>
            {% for post in posts.items %}
                 <div class="content-section">
                    <h5> <a class="article-title" href="{{ url_for("posts.post_full", post_id = post.id) }}">{{ post.title }}</a>  </h5>
                     <small class="text-muted">{{ post.date_create.strftime("%y-%m-%d") }}</small>
                    <p> {{ post.content }} </p>
                 </div>
            {% endfor %}

            {#     to loop on the pages and display it       #}

            {% for page_num in posts.iter_pages(left_edge= 1, right_edge = 1, left_current = 1, right_current= 2) %}
                {% if page_num %}
                    {% if page_num == posts.page %}
                        <a class="btn btn-info mb-4" href="{{ url_for("users.account", page = page_num, user_id = current_user.id) }}">{{ page_num }}</a>
                    {% else %}
                        <a class="btn btn-outline-info" href="{{ url_for("users.account", user_id = current_user.id, page = page_num) }}">{{ page_num }}</a>
                    {% endif %}
                {% else %}
                    ...
                {% endif %}
            {% endfor %}

            {#        end loop        #}


            <br>
                <a class="btn btn-primary" href="{{ url_for("posts.Post_page") }}"> New Post </a>
            <br>
        </div>
    </div>
    {% else %}
        <div class="container">
            <div class = "content-section">
                <h2> You don't make any Post Yet </h2>
                <br>
                <a class="btn btn-primary" href="{{ url_for("posts.Post_page") }}"> New Post </a>
            </div>
        </div>
    {% endif %}
    {% endif %}

{% endblock %}

appname/templates/account_another.html
{% extends "base.html" %}
{% block body %}
    <div class="container">
        <div class = "content-section">
        <br>
            <div class = "media">
                <img alt = "account image"  class="rounded-circle account-img" src = "{{ url_for("static", filename= "/imgs/profile_images/"+ user.image_file) }}">
                <div class="media-body">
                    <h2 class="account-heading">{{ user.username }}</h2>
                    <p class="text-secondary">{{ user.email }}</p>
                </div>
            </div>
        </div>
    </div>


    {% if posts.items %}
    <div class="container">
        <div class = "content-section">
            <h2> Posts </h2>
            {% for post in posts.items %}
                 <div class="content-section">
                    <h5> <a class="article-title" href="{{ url_for("posts.post_full", post_id = post.id) }}">{{ post.title }}</a></h5>
                     <small class="text-muted">{{ post.date_create.strftime("%y-%m-%d") }}</small>
                    <p> {{ post.content }} </p>
                 </div>
            {% endfor %}
        </div>
    </div>
        {#     to loop on the pages and display it       #}
        {% for page_num in posts.iter_pages() %}
            {% if page_num %}
                {% if page_num == posts.page %}
                    <a class="btn btn-info mb-4" href="{{ url_for("users.account_view", page = page_num, user_id = posts.items[0].author.id) }}">{{ page_num }}</a>
                {% else %}
                    <a class="btn btn-outline-info" href="{{ url_for("users.account_view", user_id = posts.items[0].author.id, page = page_num) }}">{{ page_num }}</a>
                {% endif %}
            {% else %}
                ...
            {% endif %}
        {% endfor %}
        {#        end loop        #}

    {% else %}
        <div class="container">
            <div class = "content-section">
                <h2> He Doesn't create any post yet </h2>
            </div>
        </div>
    {% endif %}

{% endblock %}

appname/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='master_mario.css') }}">
    <!-- to add anything as you want in head -->
    {% block head %}
    {% endblock %}

    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Flask Blog</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{{ url_for("main.homepage") }}">Mario Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for("main.homepage") }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for("main.about") }}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                    <a class="nav-item nav-link" href = "{{ url_for("posts.Post_page") }}">New Post</a>
                    <a class="nav-item nav-link" href = "{{ url_for("users.logout") }}">Logout</a>
                    <a class="nav-item nav-link" href = "{{ url_for("users.account", user_id = current_user.id) }}">Account</a>
                {% else %}
                    <a class="nav-item nav-link" href="{{ url_for("users.login") }}">Login</a>
                    <a class="nav-item nav-link" href="{{ url_for("users.signup") }}">Register</a>
                {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">

          {% with messeages = get_flashed_messages(with_categories = true) %}
              {% if messeages %}
                  {% for gategory,message  in messeages %}
                      <div class = "alert alert-{{ gategory }}">
                        {{ message }}
                      </div>
                  {% endfor %}
              {% endif %}
          {% endwith %}
          {% block body %}
          {% endblock %}
        </div>
      <!-- side bar -->
      {% block sidebar %}
        <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div>
      {% endblock %}
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

appname/templates/homepage.html
{% extends "base.html" %}
    {% block body %}
        {% for post in posts.items %}
            <div class="container">
                <article class="media content-section">
                    {% if post.author.username == current_user.username %}
                        <a href="{{ url_for("users.account", user_id = post.author.id) }}"> <img class="rounded-circle article-img" src = "{{ url_for("static", filename= "imgs/profile_images/" + post.author.image_file) }}"></a>
                    {% else %}
                        <a href="{{ url_for("users.account_view", user_id = post.author.id) }}"> <img class="rounded-circle article-img" src = "{{ url_for("static", filename= "imgs/profile_images/" + post.author.image_file) }}"></a>
                    {% endif %}
                    <div class="media-body">
                        <div class="article-metadata">
                            {% if current_user == post.author%}
                                <a class="mr-2" href="{{ url_for("users.account", user_id = post.author.id) }}">{{ post.author.username }} </a>
                            {% else %}
                                <a class="mr-2" href="{{ url_for("users.account_view", user_id = post.author.id) }}">{{ post.author.username }} </a>
                            {% endif %}
                            <small class="text-muted">{{ post.date_create.strftime("%y-%m-%d") }}</small>
                            <h2><a class="article-title" href="{{ url_for("posts.post_full", post_id = post.id) }}">{{ post.title }} </a> </h2>
                            <p class="article-content"> {{ post.content }} </p>
                        </div>
                    </div>
                </article>
            </div>
        {% endfor %}
        {% for page_num in posts.iter_pages(left_edge= 1, right_edge = 1, left_current = 1, right_current= 2) %}
            {% if page_num %}
                {% if page_num == posts.page %}
                    <a class="btn btn-info mb-4" href="{{ url_for("main.homepage", page = page_num) }}">{{ page_num }}</a>
                {% else %}
                    <a class="btn btn-outline-info" href="{{ url_for("main.homepage", page = page_num) }}">{{ page_num }}</a>
                {% endif %}
            {% else %}
                ...
            {% endif %}
        {% endfor %}
    {% endblock %}

appname/templates/login_page.html
{% extends 'base.html' %}
{% block sidebar %}
{% endblock %}
{% block body %}
    <div class="container">
        <div class = "content-section">
            <form method="post" action="" novalidate>
                {{ form_login.hidden_tag() }}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Login</legend>
                      <div class="form-group" >
                          {{ form_login.email.label(class = "form-control-label") }}
                          {% if form_login.email.errors %}
                              {{ form_login.email(class = "form-control is-invalid") }}
                              <div class = "invalid-feedback">
                                  {% for error in form_login.email.errors %}
                                      <span> {{ error }} </span>
                                  {% endfor %}
                              </div>
                           {% else %}
                              {{ form_login.email(class = "form-control") }}
                          {% endif %}
                      </div>
                      <div class="form-group">
                          {{ form_login.password.label(class = "form-control-label") }}
                          {% if form_login.password.errors %}
                              {{ form_login.password(class = "form-control is-invalid") }}
                              <div class = "invalid-feedback">
                                  {% for error in form_login.password.errors %}
                                      <span> {{ error }} </span>
                                  {% endfor %}
                              </div>
                           {% else %}
                              {{ form_login.password(class = "form-control") }}
                          {% endif %}
                      </div>
                      <div class="form-check">
                          {{ form_login.remember_me(class = "form-check-input") }}
                          {{ form_login.remember_me.label(class = "form-check-label")}}
                      </div>
                            <br>
                        {{ form_login.submit(class="btn btn-primary") }}
                    </fieldset>
                </form>
                <br>
            <small class="text-muted">
            <a href = "{{ url_for("users.forget_password") }}">Forget Password ?</a>
            </small>
            <div>
                <small class="text-muted">
                    Don't have an account ? <a href="{{ url_for("users.signup") }}"> Sign Up </a>
                </small>
            </div>
        </div>
    </div>
{% endblock %}